### ISSUE TITLE
User can select body part they will train

### ISSUE THREAD

**Issue by nathan-uch** [nathan-uch/workout_tracker#1]
## 💰 Motivation
Users can select which body part to train that day. All exercises shown will be according to the body part chosen.

## 📐 Plan
Users pick body part to train

## ✅ Task List

- [ ] Create and style modal 
- [ ] Add a select dropdown for body parts you can train, include a full body option
- [ ] Add a cancel and submit button
- [ ] Add event listener to cancel button hiding modal
- [ ] Add event listener to submit button which stores the body part
- [ ] Test functionality and log data to see if body part is saved
