### ISSUE TITLE
Users can add rows to the table

### ISSUE THREAD

**Issue by nathan-uch** [nathan-uch/workout_tracker#2]
## 💰 Motivation
Users can add each exercise they do

## 📐 Plan
Create a table headers and rows for exercises

## ✅ Task List

- [ ] Create a table with headers for exercises, including: 
- exercise
- body part
- equipment
- sets
- reps
- weight
- volume
- [ ] Create an add row button next to each row
- [ ] Create function for DOM tree for each row according to number of columns
- [ ] Add event listener which adds the tree to the table
- [ ] Test that adding a row will only add the correct number of rows
- [ ] Create function which, when adding a row, creates an object for the exercise (constructor or prototype) including properties for each column
