### ISSUE TITLE
Users can pick exercises and equipment

### ISSUE THREAD

**Issue by nathan-uch** [nathan-uch/workout_tracker#3]
## 💰 Motivation
After adding a row, users should be able to select an exercise according to the training body parts.

## 📐 Plan
The first column of the row will display options for exercises. This automatically updates the second column showing the body part and also adds equipment options for the exercise.

## ✅ Task List

- [ ] Add an input select for the first column of each row
- [ ] Create a DOM tree with the options of exercises according to the body part selected from modal
- [ ] If full body is chosen, all exercise options are available
- [ ] Add 'input' event listener to the first column that updates the second column showing the body part that is being trained with that exercise
- [ ] From event listener of the exercise (1st column), add available options for equipment: barbell, dumbbell, machine, v-bar, ez-bar, rope, etc.
- [ ] Update all object property values according to their event listeners
- [ ] Fix styling for rows, columns and inputs
- [ ] Test functionality
