### ISSUE TITLE
User can save, edit and personalize table

### ISSUE THREAD

**Issue by nathan-uch** [nathan-uch/workout_tracker#4]
## Motivation
Users should be able to save progress without accidentally editing the table and further personalize the table.

## Plan
Users can save exercises once they are finished, they can edit it again even after saved, can change weight units and can add multiple sets and reps for an exercise.

## Task List
- [ ] Add save button to each row that will make all values unchangeable
- [ ] Add edit button that allows user to change values again
- [ ] Add delete button to each row (also deletes object)
- [ ] Add hide button for certain columns: body part, equipment
- [ ] Add button to show hidden columns again
- [ ] Add button to change weight units (lbs or kgs)
- [ ] Changing weight units will update volume
- [ ] Can add multiple sets, reps and weight (deload), also updates total volume
- [ ] Displays total volume by body part
- [ ] Add button to save full day workout (all exercises)
